// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressController from "./address_controller.js"
application.register("address", AddressController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import ListingMapController from "./listing_map_controller.js"
application.register("listing-map", ListingMapController)

import MenuController from "./menu_controller.js"
application.register("menu", MenuController)

import RoomController from "./room_controller.js"
application.register("room", RoomController)
